-- Get a list of databases
-- SELECT datname
 -- FROM pg_database
 -- WHERE datistemplate = false;
 --psql -h localhost -p 5432 -U postgres test
-- \q quit
-- \c <database> connect
-- \l list databases
-- drop database test
-- \d list tables
